security:
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto
    App\Entity\User:
      algorithm: auto
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    dev:
      anonymous: true
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login

    guard:
      custom_authenticator: App\Security\AppCustomAuthenticator
      logout:
        path: app_logout
        target: app_login
  access_control:
    - path: ^(?!/(login|register))
      roles: IS_AUTHENTICATED_FULLY
